### PR TITLE
docs minor edits, typo fixes

### PR DESCRIPTION
**Pull request by markdly**
Nice package - I wish I'd know about it 6 months ago!

I've made a few minor edits and typo fixes to the documentation in case it helps...

### CODE REVIEW

**Comment by jonocarroll** [comment]
`_contruct` while you're at it.

`devtools::spell_check()` if you want to catch a few more.

Cheers!

**Comment by MilesMcBain** [comment]
Whoah! I am humbled. Thanks so much @markdly!

**Comment by markdly** [comment]
Ummmm maybe hold off reviewing for a bit. There's a few more on the way (now I know about `devtools::spell_check()`). 

Pls let me know if there's a `devtools:autocorrect()` I don't know about!

**Comment by markdly** [comment]
That's it from me for today!

**Comment by MilesMcBain** [comment]
Thankyou :+1:, you're added as a contributor in DESCRIPTION, feel free to add your email if you like.

**Pull request merged**
