### PR TITLE
Fixed spelling.

### PR DESCRIPTION
**Pull request by DataWookie**
Hi Miles,

Datapasta is great. I noticed a spelling mistake (I think) in the README file. Fixed here.

Thanks,
Andrew.

### CODE REVIEW

**Comment by jonocarroll** [comment]
Cheers! This should be fine as-is, but how would you feel about running `devtools::spell_check()` as well and seeing what else you can find?

**Comment by DataWookie** [comment]
Just had a check and nothing substantial. Some UK spelling (which I am actually in favour of).

**Comment by MilesMcBain** [comment]
Thanks so much for your help Andrew!

**Comment by MilesMcBain** [comment]
@DataWookie You're added as a contributor in description, feel free to PR your email.

**Pull request merged**
