### PR TITLE
Fix NAMESPACE and testing issues

### PR DESCRIPTION
**Pull request by mdlincoln**
Neat package, and thanks for using clipr!

I'm releasing a bugfix for clipr and couldn't get datapasta to pass tests on my local machine. It looks like a few functions that are used in the tests weren't ever `@export`ed. I also added a few `skip_if_not(rstudioapi::isAvailable())` to tests that relied on the api being available.

### CODE REVIEW

**Comment by MilesMcBain** [comment]
Thanks for testing downstream :+1: 

Skips make sense.

I don't really want to export those functions since they don't do much useful and will just pollute the namespace. I am thinking that the best way is probably to use the `datapasta:::` prefix in the tests. What do you reckon?

**Comment by MilesMcBain** [comment]
I also had a bit of a poke around to look at best practice and it seems that Hadley has done similar types of things in `readr`. For example `col_spec_standardise` an unexported function defined here: https://github.com/tidyverse/readr/blob/d98b6862acc49575d2bbafd4ca0389f17ce4c4f9/R/col_types.R#L217

and tested without namespace qualifier here: https://github.com/tidyverse/readr/blob/37d6eda5b2e52707bfa6ea2db8d52e0209796615/tests/testthat/test-col-spec.R#L4

Since these tests worked on my machine I'm wondering what might be different about our test workflow. I use `devtools::load_all()` and `dev_tools::test()` from RStudio and have had no problems.

**Comment by MilesMcBain** [comment]
P.S. it goes without saying that I am very happy to be using `clipr` thanks a bunch :)

**Comment by mdlincoln** [comment]
ahhh, interesting - I was doing devtools::test() in Rstudio after simply building & loading the package, which merely calls `library(datapasta)` and doesn't add unexported objects to the namespace. Lesson learned! #curseyouNAMESPACE

And I know more than I care to know about skipping tests, having been in test hell with clipr...

**Comment by MilesMcBain** [comment]
Haha yeah everything that is great about `clipr` is everything that makes it difficult to test. This package is much the same.

The pull looks good now. Welcome to datapasta contributors.

**Pull request merged**
