### PR TITLE
keep meaningful rownames when using df/tribble_paste with input_table

### PR DESCRIPTION
**Pull request by sowla**
- meaningful as in not row numbers
- add test in test_dfpaste

### CODE REVIEW

**Comment by jonocarroll** [comment]
This looks great and works largely as expected. Finaly say belongs to @MilesMcBain.

What about explicitly renaming the rownames column `"rownames"` for `dt_paste()`? The flow is the same as for `df_paste()` but a new `"row.names"` column is created as they aren't supported in `data.table` either. For consistency with `"tibble_paste()` perhaps `"rownames"` is better.

Also, what about an option to turn these off, e.g. `rownames = FALSE` defaulting to `TRUE` for `df_paste()` and `FALSE` for `tibble_paste()` and `dt_paste()`? Some documentation in each function about `rownames` would also be useful.

Thanks and congrats on the PR.

**Comment by MilesMcBain** [comment]
Thankyou very much @sowla! 😄 😄 😄 

I've had a quick look and I'm liking what I've seen. I think the `data.frame` implementation is good but I have a hesitation about including them for `tibble` and `data.table` since they're not supported in those data structures. I'll have a bit more of a think about this. I'll get back to you by the end of the week.

**Comment by sowla** [comment]
Thank you both for the feedback!! I'll wait for Miles' answer before changing anything else :)

**Comment by sowla** [comment]
Oops, I forgot to handle `input_table`s with no rownames in my earlier commit. I've added an `ifelse` and corresponding test :)

**Comment by MilesMcBain** [comment]
I've come to the conclusion that there's no need to support row names in tibbles and data.tables. My rationale is that when you convert a `data.frame` with `as_tibble()` or `as.data.table()` the row names are silently dropped. This is the convention that users expect and they have convenient tools to introduce the row names as columns if they care about them, e.g. `dplyr::add_rownames()`.

@sowla can you please:

*  remove the code that adds row name support `tribble_construct()` and the corresponding test. 
* add a check in `dfdt_construct()` that the class is `data.frame` before adding the row names. You're basically assured this since data.table doesn't have that attribute, but someone could do something weird like add it manually - and it makes the code clear that that applies to data.frames only.
* add yourself to  DESCRIPTION as an author. 😄

**Comment by sowla** [comment]
Thank you @MilesMcBain!! I see where you’re coming from :)

One question about checking the `data.frame` class.. I was thinking of using `!data.table::is.data.table`, but this doesn’t seem important enough to be worth adding a dependency..? But `is.data.frame` returns `TRUE` for `data.frame`, `data.table` and `tibble`.. is there a different function you would recommend?

Other than that I think I can push the commits tonight!

**Comment by MilesMcBain** [comment]
@sowla to assert an object has a class you can do `is(object, "class")` so you could use `!is(input_table, "data.frame") & !is(input_table, "data.table")`.

**Comment by sowla** [comment]
Perfect, thank you! :) And really sorry to bother you with that..

I think this should be it now. I don't know if I've added too many tests.. of course, please feel free to delete/edit anything!

**Comment by MilesMcBain** [comment]
I don't know if there is such a thing as too many tests. It's always nice to get PRs with tests!

**Comment by sowla** [comment]
Yay, thank you both!! :)

**Pull request merged**
